# Generated by Django 3.2.4 on 2021-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20210617_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='uid',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='uid',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
