# Generated by Django 3.2.4 on 2021-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210618_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='uid',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
