# Generated by Django 3.2.4 on 2021-06-19 00:54

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_exchange_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=64, validators=[authentication.validators.validate_special_char]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, unique=True, validators=[authentication.validators.validate_special_char]),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fund_account_bank',
            field=models.CharField(max_length=25, validators=[authentication.validators.validate_special_char]),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='fund_account_name',
            field=models.CharField(max_length=25, validators=[authentication.validators.validate_special_char]),
        ),
    ]
