# Generated by Django 3.2.4 on 2021-06-19 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20210619_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangetransaction',
            options={'ordering': ['created']},
        ),
    ]
