# Generated by Django 3.2.4 on 2021-06-15 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phoneno', models.CharField(help_text='Enter a correct phone number', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Your phone number is not in the right format', regex='^\\+(?:[0-9] ?){6,14}[0-9]$')])),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('1', 'Level 0'), ('2', 'Level 1'), ('3', 'Level 2'), ('4', 'Level 3')], default='1', max_length=1)),
                ('confirmed_email', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('confirmed_phoneno', models.BooleanField(default=False)),
                ('confirmed_id', models.BooleanField(default=False)),
                ('confirmed_address', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('0', 'Not selected'), ('1', 'Male'), ('2', 'Female')], default='0', max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='profiles')),
                ('id_photo', models.ImageField(blank=True, upload_to='user_ids')),
                ('photo', models.ImageField(blank=True, upload_to='user_faces')),
                ('address', models.TextField(blank=True)),
                ('bank_statement', models.ImageField(blank=True, upload_to='address')),
                ('country', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='authentication.user')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
