# Generated by Django 3.2.4 on 2021-06-16 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210616_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(blank=True, help_text='Enter a correct phone number', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Your phone number is not in the right format', regex='^\\+(?:[0-9] ?){6,14}[0-9]$')]),
        ),
    ]
