# Generated by Django 3.2.4 on 2021-06-18 20:44

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=15, validators=[authentication.validators.validate_special_char]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=15, validators=[authentication.validators.validate_special_char]),
        ),
    ]
